# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170318_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PERSONAL', 'personal')], default='personal', max_length=120),
        ),
    ]
