# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_question_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(default='Thinking.', max_length=120),
        ),
    ]
